FROM python:3.11-slim-buster

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your bot's code
COPY . .

# Expose any ports if your bot needs to listen (unlikely for a Discord bot)
# ENV PORT 8000
# EXPOSE 8000

# Command to run your bot
CMD ["python", "discord_bot.py"]